import { watchFile, unwatchFile } from "fs";
import chalk from "chalk";
import { fileURLToPath } from "url";
import fs from "fs";
import cheerio from 'cheerio';
import fetch from "node-fetch";
import axios from "axios";
import moment from "moment-timezone";
global.isBaileysFail = false;
global.mods = ['5493873655135'];
global.prems = ['5493873655135'];
global.obtenerQrWeb = 0; 
global.keepAliveRender = 0; 
global.botNumberCode = "5493873655168";
global.confirmCode = "5493873655168";
global.version_language = '1.0';
global.official = [["5493873655135", 'ᴍʙᴍᴅ • ᵇᵒᵗ', 1], ["5493873655168", 'ᴍʙᴍᴅ • ᵖʳⁱⁿᶜⁱᵖᵃˡ', 1]];
global.owner = [["5493873655135", '🗿 ᴏᴡɴᴇʀ', true], ["5493873655168"]];
global.gmailbot = 'mbmdoficial@gmail.com';
global.packname = `𝘞𝘩𝘢𝘵𝘴𝘈𝘱𝘱`;
global.author = `𝙈𝘽𝙈𝘿`;
global.version = "3.5.0";
global.mb_desc = "• 🅼🄱︎🅼🄳 •︎";
global.seguircanal = { channelMb: '120363368769201105@newsletter', channelMb2: '120363318353263389@newsletter' };
global.wm = "𝘔𝘉𝘔𝘋";
global.igfg = "𝑷𝒐𝒘𝒆𝒓𝒆𝒅 𝒃𝒚 𝑴𝑩𝑴𝑫.";
global.nomorown = "5493873655135";
global.Key360 = ["Gata_Dios"];
global.openai_key = 'sk-0';
global.openai_org_id = 'org-3';
global.keysZens = ["LuOlangNgentot", "c2459db922", "37CC845916", "6fb0eff124", "hdiiofficial", "fiktod", "BF39D349845E", "675e34de8a", "0b917b905e6f"];
global.keysxxx = keysZens[Math.floor(keysZens.length * Math.random())];
global.keysxteammm = ["29d4b59a4aa687ca", "5LTV57azwaid7dXfz5fzJu", "cb15ed422c71a2fb", "5bd33b276d41d6b4", "HIRO", "kurrxd09", "ebb6251cc00f9c63"];
global.keysxteam = keysxteammm[Math.floor(keysxteammm.length * Math.random())];
global.keysneoxrrr = ["5VC9rvNx", "cfALv5"];
global.keysneoxr = keysneoxrrr[Math.floor(keysneoxrrr.length * Math.random())];
global.lolkeysapi = "GataDiosV3";
global.itsrose = ["4b146102c4d500809da9d1ff"];
global.baileys = "@whiskeysockets/baileys";
global.apis = 'https://deliriussapi-oficial.vercel.app';
global.APIs = { xteam: 'https://api.xteam.xyz', dzx: 'https://api.dhamzxploit.my.id', lol: 'https://api.lolhuman.xyz', violetics: 'https://violetics.pw', neoxr: 'https://api.neoxr.my.id', zenzapis: 'https://api.zahwazein.xyz', akuari: 'https://api.akuari.my.id', akuari2: 'https://apimu.my.id', fgmods: 'https://api.fgmods.xyz', botcahx: 'https://api.botcahx.biz.id', ibeng: 'https://api.ibeng.tech/docs', rose: 'https://api.itsrose.site', popcat : 'https://api.popcat.xyz', xcoders : 'https://api-xcoders.site' },
global.APIKeys = { 'https://api.xteam.xyz': `${keysxteam}`, 'https://api.lolhuman.xyz': `${lolkeysapi}`, 'https://api.neoxr.my.id': `${keysneoxr}`, 'https://violetics.pw': 'beta', 'https://api.zahwazein.xyz': `${keysxxx}`, 'https://api.fgmods.xyz': 'DRLg5kY7', 'https://api-fgmods.ddns.net': 'fg-dylux', 'https://api.botcahx.biz.id': 'Admin', 'https://api.ibeng.tech/docs': 'tamvan', 'https://api.itsrose.site': 'Rs-Zeltoria', 'https://api-xcoders.site': 'Frieren' }
global.cheerio = cheerio;
global.fs = fs;
global.fetch = fetch;
global.axios = axios;
global.moment = moment;
global.mail = '';
global.desc = '' ;
global.desc2 = '';
global.country = '';
global.pdoc = ["application/vnd.openxmlformats-officedocument.presentationml.presentation", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.ms-excel", "application/msword", "application/pdf", "text/rtf"];
global.flaaa = [ 'https://flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=water-logo&script=water-logo&fontsize=90&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&fillTextColor=%23000&shadowGlowColor=%23000&backgroundColor=%23000&text=', 'https://flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=crafts-logo&fontsize=90&doScale=true&scaleWidth=800&scaleHeight=500&text=', 'https://flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=amped-logo&doScale=true&scaleWidth=800&scaleHeight=500&text=', 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=sketch-name&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&fillTextType=1&fillTextPattern=Warning!&text=', 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=sketch-name&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&fillTextType=1&fillTextPattern=Warning!&fillColor1Color=%23f2aa4c&fillColor2Color=%23f2aa4c&fillColor3Color=%23f2aa4c&fillColor4Color=%23f2aa4c&fillColor5Color=%23f2aa4c&fillColor6Color=%23f2aa4c&fillColor7Color=%23f2aa4c&fillColor8Color=%23f2aa4c&fillColor9Color=%23f2aa4c&fillColor10Color=%23f2aa4c&fillOutlineColor=%23f2aa4c&fillOutline2Color=%23f2aa4c&backgroundColor=%23101820&text=' ];
global.multiplier = 85;
let file = fileURLToPath(import.meta.url);
watchFile(file, () => {
unwatchFile(file);
console.log(chalk.redBright("Update 'config.js'"));
import(`${file}?update=${Date.now()}`);
});

